<?php
vc_map(array(
    "name" 			=>__("Advanced Promo", "awavcl"),
    "category" 		=> 'Advanced Elements',
    "description"	=> "Simple promo box",
    "base" 			=> "awavc_promo",
    "class" 		=> "",
    "icon" 			=> "awavc-promo-icon",

    "params" 	=> array(

        array(
            "type" => "dropdown",
            "class" => "",
            "heading" => __("Styles", "awavcl"),
            "param_name" => "promo_box",
            "admin_label"        => true,
            "value" => array(
                __("Style 1","awavcl") => 'promo1',
                __("Style 2","awavcl") => 'promo2',
                __("Style 3","awavcl") => 'promo3',
                __("Style 4","awavcl") => 'promo4',
                __("Style 5","awavcl") => 'promo5',
                __("Style 6","awavcl") => 'promo6',
            ),
           ),
        
        array(
            "type" => "attach_image",
            "heading" => __("Promo Image", "awavcl"),
            "param_name" => "promo_img",
            "value" => "",
            "description" => __("select image", "awavcl"),
        ),
        array(
            "type" => "textfield",
            "heading" => __("Promo Text 1", 'awavcl'),
            "param_name" => "pt_text1",
            "description" => __("", 'awavcl'),
            "value" => __("Waiting For What!", 'awavcl'),
            ),
        
        array(
        "type"              => "dropdown",
        "heading"           => __( "Custom Font Family (on offer Text)", "awavc" ),
        "param_name"        => "font_family",
        "value"             => array(
            "Theme Default" => "",
            "ABeeZee" => "ABeeZee",
            "Abel" => "Abel",
            "Abril Fatface" => "Abril+Fatface",
            "Aclonica" => "Aclonica",
            "Acme" => "Acme",
            "Actor" => "Actor",
            "Adamina" => "Adamina",
            "Advent Pro" => "Advent+Pro",
            "Aguafina Script" => "Aguafina+Script",
            "Akronim" => "Akronim",
            "Aladin" => "Aladin",
            "Aldrich" => "Aldrich",
            "Alegreya" => "Alegreya",
            "Alegreya SC" => "Alegreya+SC",
            "Alex Brush" => "Alex+Brush",
            "Alfa Slab One" => "Alfa+Slab+One",
            "Alice" => "Alice",
            "Alike" => "Alike",
            "Alike Angular" => "Alike+Angular",
            "Allan" => "Allan",
            "Allerta" => "Allerta",
            "Allerta Stencil" => "Allerta+Stencil",
            "Allura" => "Allura",
            "Almendra" => "Almendra",
            "Almendra Display" => "Almendra+Display",
            "Almendra SC" => "Almendra+SC",
            "Amarante" => "Amarante",
            "Amaranth" => "Amaranth",
            "Amatic SC" => "Amatic+SC",
            "Amethysta" => "Amethysta",
            "Anaheim" => "Anaheim",
            "Andada" => "Andada",
            "Andika" => "Andika",
            "Angkor" => "Angkor",
            "Annie Use Your Telescope" => "Annie+Use+Your+Telescope",
            "Anonymous Pro" => "Anonymous+Pro",
            "Antic" => "Antic",
            "Antic Didone" => "Antic+Didone",
            "Antic Slab" => "Antic+Slab",
            "Anton" => "Anton",
            "Arapey" => "Arapey",
            "Arbutus" => "Arbutus",
            "Arbutus Slab" => "Arbutus+Slab",
            "Architects Daughter" => "Architects+Daughter",
            "Archivo Black" => "Archivo+Black",
            "Archivo Narrow" => "Archivo+Narrow",
            "Arimo" => "Arimo",
            "Arizonia" => "Arizonia",
            "Armata" => "Armata",
            "Artifika" => "Artifika",
            "Arvo" => "Arvo",
            "Asap" => "Asap",
            "Asset" => "Asset",
            "Astloch" => "Astloch",
            "Asul" => "Asul",
            "Atomic Age" => "Atomic+Age",
            "Aubrey" => "Aubrey",
            "Audiowide" => "Audiowide",
            "Autour One" => "Autour+One",
            "Average" => "Average",
            "Average Sans" => "Average+Sans",
            "Averia Gruesa Libre" => "Averia+Gruesa+Libre",
            "Averia Libre" => "Averia+Libre",
            "Averia Sans Libre" => "Averia+Sans+Libre",
            "Averia Serif Libre" => "Averia+Serif+Libre",
            "Bad Script" => "Bad+Script",
            "Balthazar" => "Balthazar",
            "Bangers" => "Bangers",
            "Basic" => "Basic",
            "Battambang" => "Battambang",
            "Baumans" => "Baumans",
            "Bayon" => "Bayon",
            "Belgrano" => "Belgrano",
            "Belleza" => "Belleza",
            "BenchNine" => "BenchNine",
            "Bentham" => "Bentham",
            "Berkshire Swash" => "Berkshire+Swash",
            "Bevan" => "Bevan",
            "Bigelow Rules" => "Bigelow+Rules",
            "Bigshot One" => "Bigshot+One",
            "Bilbo" => "Bilbo",
            "Bilbo Swash Caps" => "Bilbo+Swash+Caps",
            "Bitter" => "Bitter",
            "Black Ops One" => "Black+Ops+One",
            "Bokor" => "Bokor",
            "Bonbon" => "Bonbon",
            "Boogaloo" => "Boogaloo",
            "Bowlby One" => "Bowlby+One",
            "Bowlby One SC" => "Bowlby+One+SC",
            "Brawler" => "Brawler",
            "Bree Serif" => "Bree+Serif",
            "Bubblegum Sans" => "Bubblegum+Sans",
            "Bubbler One" => "Bubbler+One",
            "Buda" => "Buda",
            "Buenard" => "Buenard",
            "Butcherman" => "Butcherman",
            "Butterfly Kids" => "Butterfly+Kids",
            "Cabin" => "Cabin",
            "Cabin Condensed" => "Cabin+Condensed",
            "Cabin Sketch" => "Cabin+Sketch",
            "Caesar Dressing" => "Caesar+Dressing",
            "Cagliostro" => "Cagliostro",
            "Calligraffitti" => "Calligraffitti",
            "Cambo" => "Cambo",
            "Candal" => "Candal",
            "Cantarell" => "Cantarell",
            "Cantata One" => "Cantata+One",
            "Cantora One" => "Cantora+One",
            "Capriola" => "Capriola",
            "Cardo" => "Cardo",
            "Carme" => "Carme",
            "Carrois Gothic" => "Carrois+Gothic",
            "Carrois Gothic SC" => "Carrois+Gothic+SC",
            "Carter One" => "Carter+One",
            "Caudex" => "Caudex",
            "Cedarville Cursive" => "Cedarville+Cursive",
            "Ceviche One" => "Ceviche+One",
            "Changa One" => "Changa+One",
            "Chango" => "Chango",
            "Chau Philomene One" => "Chau+Philomene+One",
            "Chela One" => "Chela+One",
            "Chelsea Market" => "Chelsea+Market",
            "Chenla" => "Chenla",
            "Cherry Cream Soda" => "Cherry+Cream+Soda",
            "Cherry Swash" => "Cherry+Swash",
            "Chewy" => "Chewy",
            "Chicle" => "Chicle",
            "Chivo" => "Chivo",
            "Cinzel" => "Cinzel",
            "Cinzel Decorative" => "Cinzel+Decorative",
            "Clicker Script" => "Clicker+Script",
            "Coda" => "Coda",
            "Coda Caption" => "Coda+Caption",
            "Codystar" => "Codystar",
            "Combo" => "Combo",
            "Comfortaa" => "Comfortaa",
            "Coming Soon" => "Coming+Soon",
            "Concert One" => "Concert+One",
            "Condiment" => "Condiment",
            "Content" => "Content",
            "Contrail One" => "Contrail+One",
            "Convergence" => "Convergence",
            "Cookie" => "Cookie",
            "Copse" => "Copse",
            "Corben" => "Corben",
            "Courgette" => "Courgette",
            "Cousine" => "Cousine",
            "Coustard" => "Coustard",
            "Covered By Your Grace" => "Covered+By+Your+Grace",
            "Crafty Girls" => "Crafty+Girls",
            "Creepster" => "Creepster",
            "Crete Round" => "Crete+Round",
            "Crimson Text" => "Crimson+Text",
            "Croissant One" => "Croissant+One",
            "Crushed" => "Crushed",
            "Cuprum" => "Cuprum",
            "Cutive" => "Cutive",
            "Cutive Mono" => "Cutive+Mono",
            "Damion" => "Damion",
            "Dancing Script" => "Dancing+Script",
            "Dangrek" => "Dangrek",
            "Dawning of a New Day" => "Dawning+of+a+New+Day",
            "Days One" => "Days+One",
            "Delius" => "Delius",
            "Delius Swash Caps" => "Delius+Swash+Caps",
            "Delius Unicase" => "Delius+Unicase",
            "Della Respira" => "Della+Respira",
            "Denk One" => "Denk+One",
            "Devonshire" => "Devonshire",
            "Didact Gothic" => "Didact+Gothic",
            "Diplomata" => "Diplomata",
            "Diplomata SC" => "Diplomata+SC",
            "Domine" => "Domine",
            "Donegal One" => "Donegal+One",
            "Doppio One" => "Doppio+One",
            "Dorsa" => "Dorsa",
            "Dosis" => "Dosis",
            "Dr Sugiyama" => "Dr+Sugiyama",
            "Droid Sans" => "Droid+Sans",
            "Droid Sans Mono" => "Droid+Sans+Mono",
            "Droid Serif" => "Droid+Serif",
            "Duru Sans" => "Duru+Sans",
            "Dynalight" => "Dynalight",
            "EB Garamond" => "EB+Garamond",
            "Eagle Lake" => "Eagle+Lake",
            "Eater" => "Eater",
            "Economica" => "Economica",
            "Electrolize" => "Electrolize",
            "Elsie" => "Elsie",
            "Elsie Swash Caps" => "Elsie+Swash+Caps",
            "Emblema One" => "Emblema+One",
            "Emilys Candy" => "Emilys+Candy",
            "Engagement" => "Engagement",
            "Englebert" => "Englebert",
            "Enriqueta" => "Enriqueta",
            "Erica One" => "Erica+One",
            "Esteban" => "Esteban",
            "Euphoria Script" => "Euphoria+Script",
            "Ewert" => "Ewert",
            "Exo" => "Exo",
            "Expletus Sans" => "Expletus+Sans",
            "Fanwood Text" => "Fanwood+Text",
            "Fascinate" => "Fascinate",
            "Fascinate Inline" => "Fascinate+Inline",
            "Faster One" => "Faster+One",
            "Fasthand" => "Fasthand",
            "Federant" => "Federant",
            "Federo" => "Federo",
            "Felipa" => "Felipa",
            "Fenix" => "Fenix",
            "Finger Paint" => "Finger+Paint",
            "Fjalla One" => "Fjalla+One",
            "Fjord One" => "Fjord+One",
            "Flamenco" => "Flamenco",
            "Flavors" => "Flavors",
            "Fondamento" => "Fondamento",
            "Fontdiner Swanky" => "Fontdiner+Swanky",
            "Forum" => "Forum",
            "Francois One" => "Francois+One",
            "Freckle Face" => "Freckle+Face",
            "Fredericka the Great" => "Fredericka+the+Great",
            "Fredoka One" => "Fredoka+One",
            "Freehand" => "Freehand",
            "Fresca" => "Fresca",
            "Frijole" => "Frijole",
            "Fruktur" => "Fruktur",
            "Fugaz One" => "Fugaz+One",
            "GFS Didot" => "GFS+Didot",
            "GFS Neohellenic" => "GFS+Neohellenic",
            "Gabriela" => "Gabriela",
            "Gafata" => "Gafata",
            "Galdeano" => "Galdeano",
            "Galindo" => "Galindo",
            "Gentium Basic" => "Gentium+Basic",
            "Gentium Book Basic" => "Gentium+Book+Basic",
            "Geo" => "Geo",
            "Geostar" => "Geostar",
            "Geostar Fill" => "Geostar+Fill",
            "Germania One" => "Germania+One",
            "Gilda Display" => "Gilda+Display",
            "Give You Glory" => "Give+You+Glory",
            "Glass Antiqua" => "Glass+Antiqua",
            "Glegoo" => "Glegoo",
            "Gloria Hallelujah" => "Gloria+Hallelujah",
            "Goblin One" => "Goblin+One",
            "Gochi Hand" => "Gochi+Hand",
            "Gorditas" => "Gorditas",
            "Goudy Bookletter 1911" => "Goudy+Bookletter+1911",
            "Graduate" => "Graduate",
            "Grand Hotel" => "Grand+Hotel",
            "Gravitas One" => "Gravitas+One",
            "Great Vibes" => "Great+Vibes",
            "Griffy" => "Griffy",
            "Gruppo" => "Gruppo",
            "Gudea" => "Gudea",
            "Habibi" => "Habibi",
            "Hammersmith One" => "Hammersmith+One",
            "Hanalei" => "Hanalei",
            "Hanalei Fill" => "Hanalei+Fill",
            "Handlee" => "Handlee",
            "Hanuman" => "Hanuman",
            "Happy Monkey" => "Happy+Monkey",
            "Headland One" => "Headland+One",
            "Henny Penny" => "Henny+Penny",
            "Herr Von Muellerhoff" => "Herr+Von+Muellerhoff",
            "Holtwood One SC" => "Holtwood+One+SC",
            "Homemade Apple" => "Homemade+Apple",
            "Homenaje" => "Homenaje",
            "IM Fell DW Pica" => "IM+Fell+DW+Pica",
            "IM Fell DW Pica SC" => "IM+Fell+DW+Pica+SC",
            "IM Fell Double Pica" => "IM+Fell+Double+Pica",
            "IM Fell Double Pica SC" => "IM+Fell+Double+Pica+SC",
            "IM Fell English" => "IM+Fell+English",
            "IM Fell English SC" => "IM+Fell+English+SC",
            "IM Fell French Canon" => "IM+Fell+French+Canon",
            "IM Fell French Canon SC" => "IM+Fell+French+Canon+SC",
            "IM Fell Great Primer" => "IM+Fell+Great+Primer",
            "IM Fell Great Primer SC" => "IM+Fell+Great+Primer+SC",
            "Iceberg" => "Iceberg",
            "Iceland" => "Iceland",
            "Imprima" => "Imprima",
            "Inconsolata" => "Inconsolata",
            "Inder" => "Inder",
            "Indie Flower" => "Indie+Flower",
            "Inika" => "Inika",
            "Irish Grover" => "Irish+Grover",
            "Istok Web" => "Istok+Web",
            "Italiana" => "Italiana",
            "Italianno" => "Italianno",
            "Jacques Francois" => "Jacques+Francois",
            "Jacques Francois Shadow" => "Jacques+Francois+Shadow",
            "Jim Nightshade" => "Jim+Nightshade",
            "Jockey One" => "Jockey+One",
            "Jolly Lodger" => "Jolly+Lodger",
            "Josefin Sans" => "Josefin+Sans",
            "Josefin Slab" => "Josefin+Slab",
            "Joti One" => "Joti+One",
            "Judson" => "Judson",
            "Julee" => "Julee",
            "Julius Sans One" => "Julius+Sans+One",
            "Junge" => "Junge",
            "Jura" => "Jura",
            "Just Another Hand" => "Just+Another+Hand",
            "Just Me Again Down Here" => "Just+Me+Again+Down+Here",
            "Kameron" => "Kameron",
            "Karla" => "Karla",
            "Kaushan Script" => "Kaushan+Script",
            "Kavoon" => "Kavoon",
            "Keania One" => "Keania+One",
            "Kelly Slab" => "Kelly+Slab",
            "Kenia" => "Kenia",
            "Khmer" => "Khmer",
            "Kite One" => "Kite+One",
            "Knewave" => "Knewave",
            "Kotta One" => "Kotta+One",
            "Koulen" => "Koulen",
            "Kranky" => "Kranky",
            "Kreon" => "Kreon",
            "Kristi" => "Kristi",
            "Krona One" => "Krona+One",
            "La Belle Aurore" => "La+Belle+Aurore",
            "Lancelot" => "Lancelot",
            "Lato" => "Lato",
            "League Script" => "League+Script",
            "Leckerli One" => "Leckerli+One",
            "Ledger" => "Ledger",
            "Lekton" => "Lekton",
            "Lemon" => "Lemon",
            "Libre Baskerville" => "Libre+Baskerville",
            "Life Savers" => "Life+Savers",
            "Lilita One" => "Lilita+One",
            "Limelight" => "Limelight",
            "Linden Hill" => "Linden+Hill",
            "Lobster" => "Lobster",
            "Lobster Two" => "Lobster+Two",
            "Londrina Outline" => "Londrina+Outline",
            "Londrina Shadow" => "Londrina+Shadow",
            "Londrina Sketch" => "Londrina+Sketch",
            "Londrina Solid" => "Londrina+Solid",
            "Lora" => "Lora",
            "Love Ya Like A Sister" => "Love+Ya+Like+A+Sister",
            "Loved by the King" => "Loved+by+the+King",
            "Lovers Quarrel" => "Lovers+Quarrel",
            "Luckiest Guy" => "Luckiest+Guy",
            "Lusitana" => "Lusitana",
            "Lustria" => "Lustria",
            "Macondo" => "Macondo",
            "Macondo Swash Caps" => "Macondo+Swash+Caps",
            "Magra" => "Magra",
            "Maiden Orange" => "Maiden+Orange",
            "Mako" => "Mako",
            "Marcellus" => "Marcellus",
            "Marcellus SC" => "Marcellus+SC",
            "Marck Script" => "Marck+Script",
            "Margarine" => "Margarine",
            "Marko One" => "Marko+One",
            "Marmelad" => "Marmelad",
            "Marvel" => "Marvel",
            "Mate" => "Mate",
            "Mate SC" => "Mate+SC",
            "Maven Pro" => "Maven+Pro",
            "McLaren" => "McLaren",
            "Meddon" => "Meddon",
            "MedievalSharp" => "MedievalSharp",
            "Medula One" => "Medula+One",
            "Megrim" => "Megrim",
            "Meie Script" => "Meie+Script",
            "Merienda" => "Merienda",
            "Merienda One" => "Merienda+One",
            "Merriweather" => "Merriweather",
            "Merriweather Sans" => "Merriweather+Sans",
            "Metal" => "Metal",
            "Metal Mania" => "Metal+Mania",
            "Metamorphous" => "Metamorphous",
            "Metrophobic" => "Metrophobic",
            "Michroma" => "Michroma",
            "Milonga" => "Milonga",
            "Miltonian" => "Miltonian",
            "Miltonian Tattoo" => "Miltonian+Tattoo",
            "Miniver" => "Miniver",
            "Miss Fajardose" => "Miss+Fajardose",
            "Modern Antiqua" => "Modern+Antiqua",
            "Molengo" => "Molengo",
            "Molle" => "Molle",
            "Monda" => "Monda",
            "Monofett" => "Monofett",
            "Monoton" => "Monoton",
            "Monsieur La Doulaise" => "Monsieur+La+Doulaise",
            "Montaga" => "Montaga",
            "Montez" => "Montez",
            "Montserrat" => "Montserrat",
            "Montserrat Alternates" => "Montserrat+Alternates",
            "Montserrat Subrayada" => "Montserrat+Subrayada",
            "Moul" => "Moul",
            "Moulpali" => "Moulpali",
            "Mountains of Christmas" => "Mountains+of+Christmas",
            "Mouse Memoirs" => "Mouse+Memoirs",
            "Mr Bedfort" => "Mr+Bedfort",
            "Mr Dafoe" => "Mr+Dafoe",
            "Mr De Haviland" => "Mr+De+Haviland",
            "Mrs Saint Delafield" => "Mrs+Saint+Delafield",
            "Mrs Sheppards" => "Mrs+Sheppards",
            "Muli" => "Muli",
            "Mystery Quest" => "Mystery+Quest",
            "Neucha" => "Neucha",
            "Neuton" => "Neuton",
            "New Rocker" => "New+Rocker",
            "News Cycle" => "News+Cycle",
            "Niconne" => "Niconne",
            "Nixie One" => "Nixie+One",
            "Nobile" => "Nobile",
            "Nokora" => "Nokora",
            "Norican" => "Norican",
            "Nosifer" => "Nosifer",
            "Nothing You Could Do" => "Nothing+You+Could+Do",
            "Noticia Text" => "Noticia+Text",
            "Nova Cut" => "Nova+Cut",
            "Nova Flat" => "Nova+Flat",
            "Nova Mono" => "Nova+Mono",
            "Nova Oval" => "Nova+Oval",
            "Nova Round" => "Nova+Round",
            "Nova Script" => "Nova+Script",
            "Nova Slim" => "Nova+Slim",
            "Nova Square" => "Nova+Square",
            "Numans" => "Numans",
            "Nunito" => "Nunito",
            "Odor Mean Chey" => "Odor+Mean+Chey",
            "Offside" => "Offside",
            "Old Standard TT" => "Old+Standard+TT",
            "Oldenburg" => "Oldenburg",
            "Oleo Script" => "Oleo+Script",
            "Oleo Script Swash Caps" => "Oleo+Script+Swash+Caps",
            "Open Sans" => "Open+Sans",
            "Open Sans Condensed" => "Open+Sans+Condensed",
            "Oranienbaum" => "Oranienbaum",
            "Orbitron" => "Orbitron",
            "Oregano" => "Oregano",
            "Orienta" => "Orienta",
            "Original Surfer" => "Original+Surfer",
            "Oswald" => "Oswald",
            "Over the Rainbow" => "Over+the+Rainbow",
            "Overlock" => "Overlock",
            "Overlock SC" => "Overlock+SC",
            "Ovo" => "Ovo",
            "Oxygen" => "Oxygen",
            "Oxygen Mono" => "Oxygen+Mono",
            "PT Mono" => "PT+Mono",
            "PT Sans" => "PT+Sans",
            "PT Sans Caption" => "PT+Sans+Caption",
            "PT Sans Narrow" => "PT+Sans+Narrow",
            "PT Serif" => "PT+Serif",
            "PT Serif Caption" => "PT+Serif+Caption",
            "Pacifico" => "Pacifico",
            "Paprika" => "Paprika",
            "Parisienne" => "Parisienne",
            "Passero One" => "Passero+One",
            "Passion One" => "Passion+One",
            "Patrick Hand" => "Patrick+Hand",
            "Patrick Hand SC" => "Patrick+Hand+SC",
            "Patua One" => "Patua+One",
            "Paytone One" => "Paytone+One",
            "Peralta" => "Peralta",
            "Permanent Marker" => "Permanent+Marker",
            "Petit Formal Script" => "Petit+Formal+Script",
            "Petrona" => "Petrona",
            "Philosopher" => "Philosopher",
            "Piedra" => "Piedra",
            "Pinyon Script" => "Pinyon+Script",
            "Pirata One" => "Pirata+One",
            "Plaster" => "Plaster",
            "Play" => "Play",
            "Playball" => "Playball",
            "Playfair Display" => "Playfair+Display",
            "Playfair Display SC" => "Playfair+Display+SC",
            "Podkova" => "Podkova",
            "Poiret One" => "Poiret+One",
            "Poller One" => "Poller+One",
            "Poly" => "Poly",
            "Pompiere" => "Pompiere",
            "Pontano Sans" => "Pontano+Sans",
            "Port Lligat Sans" => "Port+Lligat+Sans",
            "Port Lligat Slab" => "Port+Lligat+Slab",
            "Prata" => "Prata",
            "Preahvihear" => "Preahvihear",
            "Press Start 2P" => "Press+Start+2P",
            "Princess Sofia" => "Princess+Sofia",
            "Prociono" => "Prociono",
            "Prosto One" => "Prosto+One",
            "Puritan" => "Puritan",
            "Purple Purse" => "Purple+Purse",
            "Quando" => "Quando",
            "Quantico" => "Quantico",
            "Quattrocento" => "Quattrocento",
            "Quattrocento Sans" => "Quattrocento+Sans",
            "Questrial" => "Questrial",
            "Quicksand" => "Quicksand",
            "Quintessential" => "Quintessential",
            "Qwigley" => "Qwigley",
            "Racing Sans One" => "Racing+Sans+One",
            "Radley" => "Radley",
            "Raleway" => "Raleway",
            "Raleway Dots" => "Raleway+Dots",
            "Rambla" => "Rambla",
            "Rammetto One" => "Rammetto+One",
            "Ranchers" => "Ranchers",
            "Rancho" => "Rancho",
            "Rationale" => "Rationale",
            "Redressed" => "Redressed",
            "Reenie Beanie" => "Reenie+Beanie",
            "Revalia" => "Revalia",
            "Ribeye" => "Ribeye",
            "Ribeye Marrow" => "Ribeye+Marrow",
            "Righteous" => "Righteous",
            "Risque" => "Risque",
            "Roboto" => "Roboto",
            "Roboto Condensed" => "Roboto+Condensed",
            "Rochester" => "Rochester",
            "Rock Salt" => "Rock+Salt",
            "Rokkitt" => "Rokkitt",
            "Romanesco" => "Romanesco",
            "Ropa Sans" => "Ropa+Sans",
            "Rosario" => "Rosario",
            "Rosarivo" => "Rosarivo",
            "Rouge Script" => "Rouge+Script",
            "Ruda" => "Ruda",
            "Rufina" => "Rufina",
            "Ruge Boogie" => "Ruge+Boogie",
            "Ruluko" => "Ruluko",
            "Rum Raisin" => "Rum+Raisin",
            "Ruslan Display" => "Ruslan+Display",
            "Russo One" => "Russo+One",
            "Ruthie" => "Ruthie",
            "Rye" => "Rye",
            "Sacramento" => "Sacramento",
            "Sail" => "Sail",
            "Salsa" => "Salsa",
            "Sanchez" => "Sanchez",
            "Sancreek" => "Sancreek",
            "Sansita One" => "Sansita+One",
            "Sarina" => "Sarina",
            "Satisfy" => "Satisfy",
            "Scada" => "Scada",
            "Schoolbell" => "Schoolbell",
            "Seaweed Script" => "Seaweed+Script",
            "Sevillana" => "Sevillana",
            "Seymour One" => "Seymour+One",
            "Shadows Into Light" => "Shadows+Into+Light",
            "Shadows Into Light Two" => "Shadows+Into+Light+Two",
            "Shanti" => "Shanti",
            "Share" => "Share",
            "Share Tech" => "Share+Tech",
            "Share Tech Mono" => "Share+Tech+Mono",
            "Shojumaru" => "Shojumaru",
            "Short Stack" => "Short+Stack",
            "Siemreap" => "Siemreap",
            "Sigmar One" => "Sigmar+One",
            "Signika" => "Signika",
            "Signika Negative" => "Signika+Negative",
            "Simonetta" => "Simonetta",
            "Sintony" => "Sintony",
            "Sirin Stencil" => "Sirin+Stencil",
            "Six Caps" => "Six+Caps",
            "Skranji" => "Skranji",
            "Slackey" => "Slackey",
            "Smokum" => "Smokum",
            "Smythe" => "Smythe",
            "Sniglet" => "Sniglet",
            "Snippet" => "Snippet",
            "Snowburst One" => "Snowburst+One",
            "Sofadi One" => "Sofadi+One",
            "Sofia" => "Sofia",
            "Sonsie One" => "Sonsie+One",
            "Sorts Mill Goudy" => "Sorts+Mill+Goudy",
            "Source Code Pro" => "Source+Code+Pro",
            "Source Sans Pro" => "Source+Sans+Pro",
            "Special Elite" => "Special+Elite",
            "Spicy Rice" => "Spicy+Rice",
            "Spinnaker" => "Spinnaker",
            "Spirax" => "Spirax",
            "Squada One" => "Squada+One",
            "Stalemate" => "Stalemate",
            "Stalinist One" => "Stalinist+One",
            "Stardos Stencil" => "Stardos+Stencil",
            "Stint Ultra Condensed" => "Stint+Ultra+Condensed",
            "Stint Ultra Expanded" => "Stint+Ultra+Expanded",
            "Stoke" => "Stoke",
            "Strait" => "Strait",
            "Sue Ellen Francisco" => "Sue+Ellen+Francisco",
            "Sunshiney" => "Sunshiney",
            "Supermercado One" => "Supermercado+One",
            "Suwannaphum" => "Suwannaphum",
            "Swanky and Moo Moo" => "Swanky+and+Moo+Moo",
            "Syncopate" => "Syncopate",
            "Tangerine" => "Tangerine",
            "Taprom" => "Taprom",
            "Tauri" => "Tauri",
            "Telex" => "Telex",
            "Tenor Sans" => "Tenor+Sans",
            "Text Me One" => "Text+Me+One",
            "The Girl Next Door" => "The+Girl+Next+Door",
            "Tienne" => "Tienne",
            "Tinos" => "Tinos",
            "Titan One" => "Titan+One",
            "Titillium Web" => "Titillium+Web",
            "Trade Winds" => "Trade+Winds",
            "Trocchi" => "Trocchi",
            "Trochut" => "Trochut",
            "Trykker" => "Trykker",
            "Tulpen One" => "Tulpen+One",
            "Ubuntu" => "Ubuntu",
            "Ubuntu Condensed" => "Ubuntu+Condensed",
            "Ubuntu Mono" => "Ubuntu+Mono",
            "Ultra" => "Ultra",
            "Uncial Antiqua" => "Uncial+Antiqua",
            "Underdog" => "Underdog",
            "Unica One" => "Unica+One",
            "UnifrakturCook" => "UnifrakturCook",
            "UnifrakturMaguntia" => "UnifrakturMaguntia",
            "Unkempt" => "Unkempt",
            "Unlock" => "Unlock",
            "Unna" => "Unna",
            "VT323" => "VT323",
            "Vampiro One" => "Vampiro+One",
            "Varela" => "Varela",
            "Varela Round" => "Varela+Round",
            "Vast Shadow" => "Vast+Shadow",
            "Vibur" => "Vibur",
            "Vidaloka" => "Vidaloka",
            "Viga" => "Viga",
            "Voces" => "Voces",
            "Volkhov" => "Volkhov",
            "Vollkorn" => "Vollkorn",
            "Voltaire" => "Voltaire",
            "Waiting for the Sunrise" => "Waiting+for+the+Sunrise",
            "Wallpoet" => "Wallpoet",
            "Walter Turncoat" => "Walter+Turncoat",
            "Warnes" => "Warnes",
            "Wellfleet" => "Wellfleet",
            "Wendy One" => "Wendy+One",
            "Wire One" => "Wire+One",
            "Yanone Kaffeesatz" => "Yanone+Kaffeesatz",
            "Yellowtail" => "Yellowtail",
            "Yeseva One" => "Yeseva+One",
            "Yesteryear" => "Yesteryear",
            "Zeyada" => "Zeyada",                    

        ),
        "description" 			=> "Need help to choose video check from https://fonts.google.com/ ",
        "group" 			=> "Settings",
        
        ),
        array(
            "type" => "textfield",
            "heading" => __("Promo Text 2", 'awavcl'),
            "param_name" => "pt_text2",
            "description" => __("", 'awavcl'),
            "value" => __("50% Off ", 'awavcl'),
            ),
        array(
            "type" => "textfield",
            "heading" => __("Promo Text 3", 'awavcl'),
            "param_name" => "pt_text3",
            "description" => __("", 'awavcl'),
            "value" => __("The world's most stylish women are", 'awavcl'),
            "dependency"    => array( 'element' => "promo_box", 'value' => array('promo2','promo4') ),
            ),
            
        array(
            "type" => "vc_link",
            "heading" => __("Button Text and Link", 'awavcl'),
            "param_name" => "btn_links",
            "description" => __("", 'awavcl'),
            "value" => __("Button", 'awavcl'),
            "group" => __("Button", 'awavcl'),
            ),    
        array(
            'type'             => 'prime_slider',
            'heading'          => __( 'Promo Text 1 Font Size', 'awavcl' ),
            'param_name'       => 'pt_size1',
            "value" => 18,
            "min" => 5,
            "max" => 99,
            "step" => 1,
            "unit" => "px",
            "description" => __("", "awavcl"),
            "group" => __("Settings", 'awavcl'), 
        ),
        array(
            "type" => "dropdown",
            "class" => "",
            "heading" => __("Promo Text 1 Font Style", "awavcl"),
            "param_name" => "pt_style1",
            "admin_label"        => true,
            "value" => array(
                __("Regular","awavcl") => '',
                __("Italic","awavcl") => 'tx-italic',
            ),
            "group" => __("Settings", 'awavcl'),
           ),      
        array(
            'type'             => 'prime_slider',
            'heading'          => __( 'Promo Text 2 Font Size', 'awavcl' ),
            'param_name'       => 'pt_size2',
            "value" => 32,
            "min" => 5,
            "max" => 99,
            "step" => 1,
            "unit" => "px",
            "description" => __("", "awavcl"),
            "group" => __("Settings", 'awavcl'),
           
        ),
        array(
            "type" => "dropdown",
            "class" => "",
            "heading" => __("Promo Text 2 Font Style", "awavcl"),
            "param_name" => "pt_style2",
            "value" => array(
                __("Regular","awavcl") => '',
                __("Italic","awavcl") => 'tx-italic',
            ),
            "group" => __("Settings", 'awavcl'),
            
           ),    
        array(
            'type'             => 'prime_slider',
            'heading'          => __( 'Promo Text 3 Font Size', 'awavcl' ),
            'param_name'       => 'pt_size3',
            "value" => 18,
            "min" => 5,
            "max" => 99,
            "step" => 1,
            "unit" => "px",
            "description" => __("", "awavcl"),
            "group" => __("Settings", 'awavcl'), 
            "dependency"    => array( 'element' => "promo_box", 'value' => array('promo2','promo4') ),
        ),
        array(
            "type" => "dropdown",
            "class" => "",
            "heading" => __("Promo Text 3 Font Style", "awavcl"),
            "param_name" => "pt_style3",
            "admin_label"        => true,
            "value" => array(
                __("Regular","awavcl") => '',
                __("Italic","awavcl") => 'tx-italic',
            ),
            "group" => __("Settings", 'awavcl'),
            "dependency"    => array( 'element' => "promo_box", 'value' => array('promo2','promo4') ),
           ),
        array(
            "type" => "dropdown",
            "class" => "",
            "heading" => __("Offer Font Weight", "awavcl"),
            "param_name" => "offer_weight",
            "value" => array(
                __("Regular","awavcl") => '400',
                __("Thin","awavcl") => '300',
                __("Semi Bold","awavcl") => '600',
                __("Bold","awavcl") => '700',
                __("Extra Bold","awavcl") => '900',
            ),
            "description" => __("Check here https://fonts.google.com/ your font having those option", "awavcl"),
            "group" => __("Settings", 'awavcl'), 
           ),
        array(
            'type'             => 'prime_slider',
            'heading'          => __( 'Button Text Size', 'awavcl' ),
            'param_name'       => 'btn_size',
            "value" => 14,
            "min" => 5,
            "max" => 99,
            "step" => 1,
            "unit" => "px",
            "description" => __("", "awavcl"),
            "group" => __("Button", 'awavcl'),
        ),
        array(
            'type'             => 'prime_slider',
            'heading'          => __( 'Button Padding', 'awavcl' ),
            'param_name'       => 'btn_pad',
            "value" => 15,
            "min" => 5,
            "max" => 99,
            "step" => 1,
            "unit" => "px",
            "description" => __("", "awavcl"),
            "group" => __("Button", 'awavcl'),
        ),
        array(
            "type" => "colorpicker",
            "heading" => __("Promo Text 1 Color", 'awavcl'),
            "param_name" => "pt_clr1",
            "value" => "",
            "group" => __("Colors", 'awavcl'),
        ),        
        array(
            "type" => "colorpicker",
            "heading" => __("Promo Text 2 Color", 'awavcl'),
            "param_name" => "pt_clr2",
            "value" => "",
            "group" => __("Colors", 'awavcl'),
           ),        
        array(
            "type" => "colorpicker",
            "heading" => __("Promo Text 3 Color", 'awavcl'),
            "param_name" => "pt_clr3",
            "value" => "",
            "group" => __("Colors", 'awavcl'),
            
            "dependency"    => array( 'element' => "promo_box", 'value' => array('promo2','promo4') ),
           ),         
        array(
            "type" => "colorpicker",
            "heading" => __("Offer Text Color On Hover", 'awavcl'),
            "param_name" => "pt_hvr",
            "value" => "",
            "group" => __("Colors", 'awavcl'),
           ),
                  
        array(
            "type" => "colorpicker",
            "heading" => __("Border Color", 'awavcl'),
            "param_name" => "brdr_clr",
            "value" => "",
            "group" => __("Colors", 'awavcl'),
           ), 
        array(
            "type" => "colorpicker",
            "heading" => __("Text Color", 'awavcl'),
            "param_name" => "btn_clr",
            "value" => "",
            "group" => __("Button", 'awavcl'),
        ),
        array(
            "type" => "colorpicker",
            "heading" => __("Button Background", 'awavcl'),
            "param_name" => "btn_bg",
            "value" => "",
            "group" => __("Button", 'awavcl'),
        ),
        array(
            "type" => "colorpicker",
            "heading" => __("Button Background On Hover", 'awavcl'),
            "param_name" => "btn_bg_hvr",
            "value" => "",
            "group" => __("Button", 'awavcl'),
        ),
        array(
            "type" => "textfield",
            "heading" => esc_attr__("Extra class name", 'awavcl'),
            "param_name" => "el_class",
            "description" => esc_attr__("If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", 'awavcl'),
        ),

    )

));

function awavc_awavc_promo_shortcode($atts, $content = null) {
    extract(shortcode_atts(array(

                //'show_btnnnn' => 'Yes',
                'promo_box' => 'promo1',
                'promo_img' => '',
                'pt_text1' => 'Waiting For What!',
                'pt_text2' => '50% Off',
                'pt_text3' => '',
                'btn_links' => '',
                'font_family' => '',
                'pt_size1' => '18px',
                'pt_style1' => '',
                'pt_size2' => '30px',
                'pt_style2' => '',
                'pt_size3' => '20px',
                'pt_style3' => '',
                'btn_size' => '18px',
                'btn_pad' => '10px',
                'pt_clr1' => '#eee',
                'pt_clr2' => '#000000',
                'pt_clr3' => '#eee',
                'pt_hvr' => '#ddd',
                'brdr_clr' => '#000000',
                'btn_clr' => '#fff;',
                'btn_bg' => '#EE2456;',
                'btn_bg_hvr' => '',
                'offer_weight' => '#4773D8',
                'el_class' => '',
    ), $atts));

    wp_register_style( 'awavcl.awavc-promo.css', plugins_url( '/css/awavc-promo.css',  __FILE__) );
    wp_enqueue_style( 'awavcl.awavc-promo.css' );
    
        $image = wp_get_attachment_image_src( $promo_img, 'full' );   
        $btn_link   = vc_build_link( $btn_links);
        $btn_url   = $btn_link['url'];
        $btn_target   = $btn_link['target'];
        $btn_title   = $btn_link['title'];
        if(empty($btn_title)){$btn_title ='Discover Now!';}
        
        
        $html = '';
            
                $add_class = (rand(9,9999));
                if( $font_family != '' ){$html .= '<style>@import url(https://fonts.googleapis.com/css?family='.$font_family.');</style>';} 
        if($promo_box == 'promo1'){
                $i = (rand(1,99));
                $html .= '
                
                <style>.awavcl-promo-box1'.$i.':hover .awavcl-promo-ttl'.$i.' {color: '.$pt_hvr.' !important;}</style>
                <div class="awavcl-promo-box1 awavcl-promo-box1'.$i.'  '.$el_class.' ">
                            <img src="'.$image[0].'" alt="image">

                            <div class="content text-white">
                                <span style="font-size:'.$pt_size1.'px;font-style:'.$pt_style1.';color:'.$pt_clr1.'; ">'.$pt_text1.'</span>
                                <h3 class="awavcl-promo-ttl'.$i.'" style="font-family:'.$font_family.';font-size:'.$pt_size2.'px;font-style:'.$pt_style2.';color:'.$pt_clr2.'; ">'.$pt_text2.'</h3>
                                <a href="pap" class="default-btn" style="color:'.$btn_clr.';font-size:'.$btn_size.'px;background-color:'.$btn_bg.';padding:'.$btn_pad.'px; ">'.$btn_title.'</a>
                            </div>
                            <a href="'.$btn_url.'" target="_blank" class="link-btn"></a>
                        </div>';      

                    } 
        if($promo_box == 'promo2'){  
            $i = (rand(9,99));  
            $html .= '    
            <style>.awavcl-promo-box2'.$i.':hover .awavcl-promo-ttl'.$i.' {color: '.$pt_hvr.' !important;}.awavcl-promo-box2'.$i.' .awavcl-desc .awavcl-title-large span::before{background:'.$brdr_clr.' !important;}.awavcl-btn'.$i.':hover {background-color:'.$btn_bg_hvr.'!important;}</style>    
                    <div class="awavcl-promo-box2 awavcl-content awavcl-promo-box2'.$i.'  '.$el_class.'  ">
                            <a href="'.$btn_url.'" class="image-box" tabindex="0">
                                <img src="'.$image[0].'" class="lazyload error" data-src="'.$image[0].'" alt="" data-was-processed="true">
                            </a>
                            <div class="awavcl-desc">
                                <a href="'.$btn_url.'" class="awavcl-title" tabindex="0">
                                    <div class="awavcl-title-small" style="font-size:'.$pt_size1.'px;font-style:'.$pt_style1.';color:'.$pt_clr1.'; ">'.$pt_text1.'</div>
                                    <div class="awavcl-title-large"><span class=" awavcl-promo-ttl'.$i.'" style="font-family:'.$font_family.';font-size:'.$pt_size2.'px;font-style:'.$pt_style2.';color:'.$pt_clr2.'; ">'.$pt_text2.'</span></div>
                                </a>
                                <p style="font-size:'.$pt_size3.'px;font-style:'.$pt_style3.';color:'.$pt_clr3.'; ">'.$pt_text3.'</p>
                                <a href="'.$btn_url.'" class="btn awavcl-btn'.$i.'" tabindex="0" style="color:'.$btn_clr.';font-size:'.$btn_size.'px;background-color:'.$btn_bg.';padding:'.$btn_pad.'px; ">'.$btn_title.'</a>
                            </div>
                        </div>';
                }   
                
                     
        if($promo_box == 'promo3'){  
            $i = (rand(9,99));  
            $html .= '    
            <style>.awavcl-promo-box3'.$i.':hover .awavcl-promo-ttl'.$i.' {color: '.$pt_hvr.' !important;}.awavcl-promo-box3'.$i.' .aw-desc.aw-promo-type1 .aw-title-large::before{background:'.$brdr_clr.' !important;}</style>    
                    
                                <a href="'.$btn_url.'" class="awavcl-promo-box3 awavcl-promo-box3'.$i.'  '.$el_class.' ">
                                    <div class="img-box">
                                        <img src="'.$image[0].'" class="lazyload loaded" data-src="'.$image[0].'" alt="" data-was-processed="true">
                                    </div>
                                    <div class="aw-desc aw-promo-type1 aw-point-v-t aw-point-h-l">
                                        <div class="aw-desc-wrapper">
                                            <div class="aw-title-large" ><span class=" awavcl-promo-ttl'.$i.'" style="font-size:'.$pt_size1.'px;font-style:'.$pt_style1.';color:'.$pt_clr1.';font-family:'.$font_family.'; ">'.$pt_text1.'</span></div>
                                            <p style="font-size:'.$pt_size2.'px;font-style:'.$pt_style2.';color:'.$pt_clr2.'; ">'.$pt_text2.'</p>
                                        </div>
                                    </div>
                                </a>
                            ';
                } 
        if($promo_box == 'promo4'){  
            $i = (rand(9,99));  
            $html .= '    
            <style>.awavcl-promo-box4'.$i.':hover .awavcl-promo-ttl'.$i.' {color: '.$pt_hvr.' !important;}.awavcl-promo-box4'.$i.' .aw-desc.aw-promo-type2 .aw-title-large::before{background:'.$brdr_clr.' !important;}.awavcl-btn'.$i.':hover {background-color:'.$btn_bg_hvr.'!important;}</style>    
                    
                                <a href="#" class="awavcl-promo-box3  awavcl-promo-box4'.$i.'  '.$el_class.' ">
                            <div class="image-box">
                                <img src="'.$image[0].'" alt="" class="loading" data-was-processed="true">
                            </div>
                            <div class="aw-desc aw-promo-type2">
                                <div class="aw-desc-wrapper text-center">
                                    <div class="aw-title-small"><span style="font-size:'.$pt_size1.'px;font-style:'.$pt_style1.';color:'.$pt_clr1.'; ">'.$pt_text1.'</span></div>
                                    <div class="aw-title-large"><span class=" awavcl-promo-ttl'.$i.'" style="font-size:'.$pt_size2.'px;font-style:'.$pt_style2.';color:'.$pt_clr2.';font-family:'.$font_family.'; ">'.$pt_text2.'</span></div>
                                    <p class="" style="font-size:'.$pt_size3.'px;font-style:'.$pt_style3.';color:'.$pt_clr3.'; ">'.$pt_text3.'</p>
                                    <div class="btn awavcl-btn'.$i.'" tabindex="0" style="color:'.$btn_clr.';font-size:'.$btn_size.'px;background-color:'.$btn_bg.';padding:'.$btn_pad.'px; ">'.$btn_title.'</div>
                                </div>
                            </div>
                        </a>
                            ';
                }  
         
                
                
    return $html;
}

add_shortcode("awavc_promo", "awavc_awavc_promo_shortcode");